name: Test Flow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker container
        run: docker build -f Dockerfile.test -t ml-env .

      - name: Get in the container, compile and RUN
        run: |
          docker run --rm -v "${PWD}:/workspace" -w /workspace ml-env bash -c "
            mkdir -p build && cd build && rm -rf * &&
            cmake -DBUILD_TESTS=ON ../ && make &&
            ctest --output-on-failure
          "
